#from legal.Importing import AppC.txt





f = open('Ivan.txt','r') # open in read mode
utf = f.read()
print utf
#data = f.read()
#print data



AllReporters = [
["A", "Atlantic Reporter", "US", 1855, 1983],
["A (2d)", "Atlantic Reporter, Second Series", "US", 1938, Present], 
["A & N", "Alcock and Napier's Reports", "I", 1831, 1833], 
["A Crim R", "Australian Criminal Reports", "AU", 1980, Present], 
["Act", "Acton's Prize Cases", "US", 1809, 1811], 
["A Int'l LC", "American International Law Cases", "US", 1793, Present], 
["ANWTYTR", "Alberta, Northwest Territories & Yukon Tax Reporter", "CA", 1973, Present], 
["AALR", "Australian Argus Law Reports", "AU", 1960, 1973], 
["AAR", "Administraive Appeal Reports", "AU", 1984, Present], 
["AAS", "Arbitrage - Santé et services sociaux", "CA (QC)", 1983, Present], 
["ABC", "Australian Bankruptcy Cases", "AU", 1928, 1964], 
["ABD", "Canada, Public SErvice Commission, Appeals and Investigation Branch, Appeal Board Decisinos", "CA", 1979, 1999], 
["AC", "Law Reports, Appeal Cases", "UK", 1890, Present], 
["ACA", "Australian Corporate Affairs Reporter", "AU", 1971, 1982], 
["ACLC", "Australian Company Law Cases", "AU", 1971, 1982], 
["ACLP", "Australian Company Law and Practice", "AU", 1981, 1991], 
["ACLR", "Australian Company Law Reports", "AU", 1974, 1989], 
["ACLR", "Australian Company Law Reporter", "AU", 1982, 1997], 
["ACSR", "Australian Coporations and Securities Reports", "AU", 1989, Present], 
["ACTR", "Autralian Capital Territory Reports", "AU (ACT)", 1973, Present], 
["ACWS", "All Canada Weekly Summaries", "CA", 1970, 1979], 
["ACWS (2d)", "All Canada Weekly Summaries (Second Series)", "CA", 1980, 1986], 
["ACWS (3d)", "All Canada Weekly Summaries (Third Series)", "CA", 1980, Present], 
["AD", "South African Law reports, Appellate Division", "S Afr", 1910, 1946], 
["Adam", "Adam's Justiciary Cases", "Scot", 1893, 1916], 
["Add", "Addams's Reports (ER vol 162)", "UK", 1822, 1826], 
["ADIL", "Annual Digest and Reports of Public International Cases", "Int'l", 1919, 1949], 
["Admin LR", "Administratice Law Reports", "CA", 1983, 1991], 
["Admin LR (2d)", "Administratice Law Reports (Second Series)", "CA", 1992, 1998], 
["Admin LR (3d)", "Administratice Law Reports (Third Series)", "CA", 1998, 2003], 
["Admin LR (4th)", "Administratice Law Reports (Fourth Series)", "CA", 2003, Present], 
["Ad & El", "Adolphus & Ellis's Reports (ER Vols 110-113)", "US", 1834, 1842], 
["ADR", "Australian De Facto Relationships Law", "AU", 1985, Present], 
["AEBR", "Australian Business & Assets Planning Reporter", "AU", 1986, Present],
["AEBCN", "Australian Business & Estate Planning Case Notes", "AU", 1979, 1981], 
["AEUB", "Alberta Energy and Utilities Board Decisions", "CA", 1995, Present], 
["Afr LR (Comm)", "African Law Reports: Commercial", "Afr", 1964, 1980], 
["Afr LR (Mal)", "African Law Reports: Malawi Series", "Afr", 1923, 1972], 
["Afr LR (SL)", "African Law Reports: Sierra Leone Series", "Afr", 1920, 1973], 
["AFTR", "Australian Federal Tax Reporter", "AU", 1969, Present], 
["AILR", "Australia Indigenous Law Reporter", "AU", 1996, Present], 
["A imm app", "Affaires d'immegration en appel", "Can", 1967, 1970], 
["A imm app (ns)", "Affaires d'immegration en appel (nouvelle série)", "Can", 1969, 1977], 
["AIN", "Australian Industrial and Intellectual Property Cases", "AU", 1982, Present], 
["AJDA", "Actualité juridique, droit administratif", "France", 1955, Present], 
["AJDI", "Actualité juridique, droit immobilier", "France", 1997, Present], 
["AJDQ", "Annuaire de jurispredenec et de doctrine du Québec", "CA (QC)", 1989, Present], 
["AJPI", "Actualité juridique, proporiété immobiliére", "France", 1955, 1997], 
["AJQ", "Annuaire de jurisprudence du Québec", "CA (QC)", 1937, 1988], 
["Al", "Aleyn's Select Cases (ER vol 82)", "UK", 1646, 1649], 
["Ala", "Alabama Reports", "US", 1840, 1946],
["Ala (NS)", "Alabama Reports (New Series)", "US", 1846, 1975], 
["Alaska Fed", "Alaska Federal Reports", "US", 1869, 1937], 
["Alaska R", "Alaska Reports", "US", 1884, 1958], 
["ALD", "Adminsitrative Law Decisions", "AU", 1976, Present], 
["ALJR", "Australian Law Journal Reports", "AU", 1958, Present], 
["All ER", "All England Reports", "UK", 1936, Present], 
["All ER (Comm)", "All England Reports (Commercial Cases)", "UK", 1999, Present], 
["All ER (EC)", "All England Law Reports (European Cases)", "UK", 1995, Present], 
["All ER Rep", "All England Reports Reporents", "UK", 1558, 1935], 
["All ER Rep Ext", "All England Reprings Extension Volumes", "UK", 1861, 1935], 
["ALLR", "Australian Law Reporter", "AU", 1977, Present], 
["ALMD", "Australian Legal Monthly Digest", "AU", 1967, Present], 
["Alta BAA", "Alberta Board of Arbitration, Arbitrations under the Alberta Labour Act", "CA (AB)", 1980, Present], 
["Alta BAAA", "Alberta Board of Adjudication, Adjudications and Arbitrations under the Public Service Employee Relations Act", "CA (AB)", 1980, 1986], 
["Alta BIR", "Alberta Board of Industrial Relations Decisions", "CA (AB)", 1961, 1982], 
["Alta ERCB", "Alberta Energy Resources Conservation Board (Decisions and Reports)", "CA (AB)", 1971, Present], 
["Alta HRCR", "Alberta Human Rights Commission, Reports of Boards of Inquiry", "CA (AB)", 1972, 19982], 
["Alta LR", "Alberta Law Reports", "CA (AB)", 1908, 1933], 
["Alta LR (2d)", "Alberta Law Reports (Second Series)", "CA (AB)", 1976, 1992], 
["Alta LR (3d)", "Alberta Law Reports (Third Series)", "CA (AB)", 1992, 2002], 
["Alta LR (4th)", "Alberta Law Reports (Fourth Series)", "CA (AB)", 2002, 2009], 
["Alta LR (5th)", "Alberta Law Reports (Fifth Series)", "CA (AB)", 2009, Present], 
["Alta LRBD", "Alberta Labour Relations Board Decisions", "CA (AB)", 1982, 1986], 
["Alta LRBR", "Alberta Labour Relations Board Reports", "CA (AB)", 1986, Present], 
["Alta OGBC", "Alberta Oil and Gas Conservation Board Decisions", "CA (AB)", 1957, 1971], 
["Alta PSERB", "Alberta Public Service Employee Relations Baord Decisions", "CA (AB)", 1981, 1986], 
["Alta PSGAB", "Alberta Public Services Grievance Appeal Board Adjudications and Arbitrations", "CA (AB)", 1980, 1985], 
["Alta PUB", "Alberta Public Utilities Board Decisions", "CA (AB)", 1976, Present],
["ALR", "Administrative Law Reports in the British Journal of Administrative Law", "UK", 1954, 1954], 
["ALR", "American Law Reports", "US", 1919, 1948], 
["ALR", "Argus Law Reports", "AU", 1895, 1959], 
["ALR", "Australian Law Reports", "AU", 1973, Present], 
["ALR (2d)", "American Law Reports (Second Series)", "US", 1948, 1965], 
["ALR (3d)", "American Law Reports (Third Series)", "US", 1965, 1980], 
["ALR (4th)", "American Law Reports (Fourth Series)", "US", 1980, 1991], 
["ALR (5th)", "American Law Reports (Fifth Series)", "US", 1992, Present], 
["Amb", "Ambler's Reports, Chancery (ER vol 27)", "UK", 1716, 1783], 
["AMC", "American Martime Cases", "US", 1923, Present], 
["And", "Anderson's Common Law Conveyancing and Equity (ER vol 123)", "UK", 1534, 1605], 
["Andr", "Andrew's Reports (ER vol 95)", "UK", 1738, 1739], 
["Ann Conv Eur DH", "Annuaire de la Convention eurpéene des droits de l'Homme", "EU", 1958, Present], 
["Anst", "Anstruther's Reports (ER vol 145)", "UK", 1792, 1797], 
["App Cas", "Appeal Cases", "UK", 1875, 1890], 
["App Div", "New York Appellate Dicision Reports", "UK", 1896, 1956], 
["App Div (2d)", "New York Appellate Dicision Reports (Second Series)", "US", 1956, Present], 
["APR", "Atnalntic Provinces Reports", "CA", 1975, Present], 
["Arb Serv Rep", "Arbitration Services Reporter", "CA", 1977, Present], 
["Ariz", "Arizona Reports", "US", 1866, Present], 
["Ark", "Arkansas Reports", "US", 1837, Present], 
["Ark App", "Arkansas Appellate Reports", "US", 1981, Present], 
["Arn", "Arnold's Reports", "UK", 1838, 1839], 
["Arn & H", "Arnold and Hodge's Reports", "UK", 1840, 1841], 
["AR", "Alberta Reports", "CA (AB)", 1976, Present], 
["ASLC", "Australian Securities Law Cases", "AU", 1971, Present], 
["ASC Sum", "Alberta Securities Commission Summaries", "CA (AB)", 1975, Present],
["Asp MLC", "Aspinall's Maritime Law Cases", "UK", 1870, 1940],
["ATB", "Canada Air Transprot Board Decisions", "CA", 1944, 1967], 
["ATC", "Australian Tax Cases", "AU", 1969, Present], 
["Atk", "Atkyns's Reports, Chancery (ER vol 26)", "UK", 1736, 1755], 
["Av Cas", "Aviation Cases", "US", 1822, Present], 
["AWLD", "Alberta Weekly Law Digest", "Can (AB)", 1982, Present], 
["B & Ad", "Barnewall & Adolphus's Reports, King's Bench (ER vols 109-110)", "UK", 1830, 1834], 
["B & Ald", "Barnewall Anderonson's Reports, King's Bench", "UK", 1817, 1822], 
["B & CR", "Reports of Bankruptcy and Companies Winding-Up Cases", "UK", 1918, 1941], 
["B & Cress", "Barnewall & Cresswell's Reports, King's Bench (ER vols 107-109)", "UK", 1822, 1830], 
["B & S", "Best & Smith's Reports (ER vols 121-122", "UK", 1861, 1865], 
["BA", "Book of Awards (Arbitration Court, Court of Appeal)", "NZ", 1894, 1991], 
["Ball & B", "Ball and Beatty's Reports", "I", 1807, 1814], 
["Barn C", "Barnardiston's Chancery Reports (ER vol 27)", "UK", 1740, 1741], 
["Barn KB", "Barnardison's King's Bench Reports (ER vol 94)", "UK", 1726, 1735], 
["Barnes", "Barnes's Notes (ER vol 94)", "UK", 1732, 1760], 
["Batt", "Batty's Reports", "I", 1825, 1826], 
["BC Empl", "British Columbia Employment Standards Board Decisions", "CA (BC)", 1981, 1983], 
["BC En Comm'n Dec", "British Columbia Energy Commission Decisions", "CA (BC)", 1977, 1980], 
["BCHRC Dec", "British Columbia Human Rights Commission Decisions", "CA (BC)", 1975, 1982], 
["BCSCW Summ", "British Columbia Securities Commission Weekly Summary", "CA (BC)", 1987, Present], 
["BC Util Comm'n", "British Columbia Utilities Commission Decisions", "CA (BC)", 1980, Preent], 
["BCAC", "British Columbia Appeal Cases", "CA (BC)", 1991, Present], 
["BCAVC", "British Columbia, Director of Trade Practices, Assurances of voluntary compliance pursuant to section 15 of the Trade PRactices Act (Decisions)", "CA (BC)", 1974, 1978], 
["BCD", "Bulletin des contributions directes, de la tace sur la valeur ajoutée et des impôts indirects", "France", 1961, 1974], 
["BCLR", "British Columbia Law Reports", "CA (BC)", 1977, 1986], 
["BCLR (2d)", "British Columbia Law Reports (Second Series)", "CA (BC)", 1986, 1995], 
["BCLR (3d)", "British Columbia Law Reports (Third Series)", "CA (BC)", 1995, 2001], 
["BCLR (4th)", "British Columbia Law Reports (Fourth Series)", "CA (BC)", 2002, Present], 
["BCLRB Dec", "British Columbia Labour Relations Board Decisions", "CA (BC)", 1979, Present], 
["B Const LR", "Butterworths Constitutional Law Reports", "S Afr", 1994, Present], 
["BCR", "British Columbia Reports", "CA (BC)", 1867, 1947], 
["BCWCR", "Brisith Columbia Workers' Compensation Reporter", "CA (BC)", 1973, Present], 
["BDM", "Bulletin de droit municipal", "CA (QC)", 1994, Present], 
["Bd Rwy Comm'rs Can", "Board of Railway Commissioners for Canada - Judgements, Orders, Regulations, and Rulings", "CA", 1911, 1938], 
["Bd Trans Comm'rs Can", "Board of Transport Commissioners for Canada - Judgements, Orders, Regulations, and Rulings", "CA", 1938, 1967], 
["Beat", "Beatty's Reports", "I", 1813, 1830], 
["Beaubien", "Beaubien", "CA (QC)", 1905, 1906], 
["Beav", "Beavan's Reports (ER vols 48-55)", "UK", 1838, 1866], 
["Bel", "Bellewe's Reports (ER vol 72)", "UK", 1378, 1400], 
["Bell", "Bell's Reports (ER vol 169)", "UK", 1858, 1860], 
["Ben & D", "Benloe & Dalison's Reports (ER vol 123)", "UK", 1486, 1580], 
["Benl", "Benloe's Reports (ER vol 73)", "UK", 1531, 1628], 
["BILC", "British International Law Cases", "UK", 1964, Present], 
["Bing", "Bingham's Reports (ER vols 130-131)", "UK", 1822, 1834], 
["Bing NC", "Bingham's New Cases (ER vols 131-133)", "UK", 1834, 1840], 
["BISD", "Basic Instruments and Selected Documents", "GATT", 1952, Present], 
["Bla H", "H Blackstone Reports", "UK", 1788, 1796], 
["Bla W", "W Blackstone Reports", "UK", 1746, 1779], 
["BLE", "Bulletin du libre-échange", "CA", 1990, 1996], 
["Bli", "Bligh's Reports, House of Lords (ER vol 4)", "UK", 1819, 1821], 
["Bli NS", "Bligh's Reports (New Series) (ER vols 4-6)", "UK", 1826, 1837], 
["BLR", "Business Law Reports", "CA", 1977, 1990], 
["BLR (2d)", "Business Law Reports (Second Series)", "CA", 1991, 1999],
["BLR (3d)", "Business Law Reports (Third Series)", "CA", 2000, 2005], 
["BLR (4th)", "Business Law Reports (Fourth Series)", "CA", 2005, Present],
["Bos & Pul", "Bosanquet & Puller's Reports (ER vols 126-127)", "UK", 1796, 1804], 
["Bos & Pul NR", "Bosanquet & Puller's New Reports (ER vol 127)", "UK", 1804, 1807], 
["BR", "Recueils de jurisprudence du Québec: Cour du Banc de la Reine / du Roi", "CA (QC)", 1892, 1941], 
["BR", "Rapports judiciaires officels de Québec: Cour du Bnc de la Reine / du Roi", "CA (QC)", 1942, 1969], 
["BREF", "Décisions du Bureau de révision de l'évaluation fonciére", "CA (QC)", 1980, 1988], 
["Bridg", "Sir John Bridgman's Conveyances", "UK", 1613, 1621], 
["Bridg Conv", "Sir Orlando Bridgman's Conveyances", "UK", 1600, 1667], 
["Bridg J", "Sir J Bridgman's Reports (ER vol 123)", "UK", 1613, 1621], 
["Bridg O", "Sir O Bridgman's Reports (ER vol 124)", "UK", 1660, 1667],
["Bro CC", "Brown's Chancery Cases (by Belt) (ER vols 28-29)", "UK", 1778, 1794], 
["Bro PC", "Brown's Parliamentary Cases (ER vols 1-3)", "UK", 1702, 1800], 
["Brod & Bing", "Broderip & Bingham's reports (ER vol 129)", "UK", 1819, 1822], 
["Brooke NC", "Brooke's New Cases (ER vol 73)", "UK", 1515, 1558], 
["Brown & Lush", "Browning & Lushington's Admirality Reports (ER vol 167)", "UK", 1863, 1867], 
["Brownl", "Brownlow & Goldesborough's Reports (ER vol 123)", "UK", 1569, 1624], 
["Bull CVMQ", "Bulletin - Commission des valeurs mobiliéres du Québec", "CA (QC)", 1970, Present], 
["Bull civ", "Bulletin des arrêts de la Cour de cassation, Chambres civiles", "France", 1798, Present], 
["Bull Concl fisc", "Bulletin des conclusions fiscales", "France", 1992, Present], 
["Bull Crim", "Bulletin des arrêts de la Cour de cassation, Chambre criminelle", "France", 1798, Present], 
["Bull OSC", "Bulletin of the Ontario Securities Commission", "CA (ON)", 1981, Present], 
["Bulst", "Bulstrode's Reports, King's Bench (ER vols 80-81)", "UK", 1609, 1626], 
["Bunb", "Bunbury's Reports, Exchequer (ER vol 145)", "UK", 1713, 1741], 
["Burr", "Burrow's Reports (ER vols 97-98)", "UK", 1756, 1772], 
["Burrell", "Burrell's Reports (ER vol 167)", "UK", 1584, 1839], 
["C & J", "Crompton & Jervis's Reports (ER vols 148-149)", "UK", 1830, 1832], 
["C & M", "Crompton & Meeson's Reports (ER vol 149)", "UK", 1832, 1834], 
["C & S", "Clarke and Scully's Drainage Cases", "CA (ON)", 1898, 1903], 
["CA", "Recueils de jurisprudence de Québec: Cour d'appel", "CA (QC)", 1970, 1985], 
["CAC", "Canada Citizenship Appeal Court, Reasons for Judgement", "CA", 1975, 1977], 
["CACM", "Recueil des arrêts de la Cour d'appeal des cours martiales", "CA", 1957, Present], 
["CAEC", "Commission d'appel de enregistrements commerciaux, Sommaires des décisions", "CA (ON)", 1971, Present], 
["CAI", "Dêcisions de la Commission d'accés á l'information", "CA (QC)", 1984, Present], 
["Cal", "California Reports", "US", 1850, 1934], 
["Cal (2d)", "California Reports (Second Series)", "US", 1934, 1969], 
["Cal (3d)", "California Reports (Third Series)", "US", 1969, 1991], 
["Cal (4th)", "California Reports (Fourt Series)", "US", 1991, Present], 
["CALP", "Décisions de la Commission d'appel en matiére de lésions professionnelles", "CA (QC)", 1986, 1998], 
["CALR", "Criminal Appeals Law Reporter", "CA", 1993, Present], 
["Calth", "Calthrop's Reports (ER vol 80)", "UK", 1609, 1618], 
["Cameron PC", "Cameron's Constitutional Decisions of the Privy Council", "CA", 1867, 1915], 
["Cameron SC", "Cameron's Supreme Court Cases", "CA", 1880, 1900], 
["Camp", "Campbell's Reports (ER vols 170-171)", "UK", 1807, 1816], 
["Cape SCR", "Supreme Court Reports (Cape)", "S Afr", 1880, 1910], 
["CAQ", "Causes en appel au Québec", "CA (QC)", 1986, 1995], 
["CAR", "Commonwealth Arbitration Reports", "AU", 1905, Present], 
["Car & K", "Carrington & Kirwan Reports (ER vols 174-175)", "UK", 1843, 1853], 
["Car & M", "Carringston & Marshman Reports (ER vol 174)", "UK", 1840, 1842], 
["Car & P", "Carringston & Payne (ER vols 171-173", "UK", 1823, 1841], 
["Carey", "Carey's Manitoba Reports", "CA (MB)", 1875, 1875], 
["Cart BNA", "Cartwright's Cases on the British Borth America Act, 1867", "CA", 1882, 1897], 
["Carter", "Carter's Reports, Common Pleas (ER vol 124)", "UK", 1664, 1676], 
["Carth", "Carthew's Reports, King's Bench (ER vol 90)", "UK", 1686, 1701], 
["Cary", "Cary's Chancery Reports (ER vol 21)", "UK", 1557, 1604], 
["CAS", "Décisions de la Commission des affaires sociales", "CA (QC)", 1975, 1997], 
["Cas t Hard", "Cases temp Hardwicke (ER vol 95)", "UK", 1733, 1738], 
["Cas t Talb", "Cases temp Talbot (ER vol 25)", "UK", 1733, 1738], 
["CB", "Common Bench Reports (ER vols 135-139)", "UK", 1845, 1856], 
["CB (NS)", "Common Bench Reports (New Series) (ER vols 140-144)", "UK", 1856, 1866], 
["CBES", "Recueils de jurisprudence du Québec: Cour du bien-être social", "CA (QC)", 1975, 1977], 
["CBR", "Copyright Board Reports", "CA", 1990, 1994], 
["CBR", "Canadian Bankruptcy Reports", "CA", 1920, 1960], 
["CBR (NS)", "Canadian Bankruptcy Reports (New Series)", "CA", 1960, 1990], 
["CBR (3d)", "Canadian Bankruptcy Reports (Third Series)", "CA", 1991, 1998], 
["CBR (4th)", "Canadian Bankruptcy Reports (Fourth Series)", "CA", 1998, 2004], 
["CBR (5th)", "Canadian Bankruptcy Reports (Fifth Series)", "CA", 2004, Present], 
["CCC", "Cashiers du Conseil constitutional", "France", 1996, Present], 
["CCC", "Canadian Criminal Cases", "CA", 1898, 1962],
["CCC (NS)", "Canadian Criminal Cases (New Series)", "CA", 1963, 1970], 
["CCC (2d)", "Canadian Criminal Cases (Second Series)", "CA", 1971, 1983], 
["CCC (3d)", "Canadian Criminal Cases (Third Series)", "CA", 1983, Present], 
["CCEL", "Canadian Cases on Employment Law", "CA", 1983, 1994],
["CCEL (2d)", "Canadian Cases on Employment Law (Second Series)", "CA", 1994, 2000], 
["CCEL (3d)", "Canadian Cases on Employment Law (Third Series)", "CA", 2000, Present], 
["CCL", "Canadian Current Law", "CA", 1948, 1990], 
["CCL", "Canadian Current Law: Jurispredence / sommaires de la jurisprudence", "CA", 1991, 1991], 
["CCL", "Canadian Current Law: Case Law Digests / sommaires de la jurisprudence", "CA", 1992, 1996], 
["CCL", "Canadian Current Law: Case Digests / sommaires de la jurisprudence", "CA", 1996, Present], 
["CCL Législation", "Canadian Current Law: Annuaire de la législation", "CA", 1989, Present], 
["CCL Legislation", "Canadian Current Law: Legislation Annual", "CA", 1989, Present], 
["CCLI", "Canadian Cases on the Law of Insurance", "CA", 1983, 1991], 
["CCLI (2d)", "Canadian Cases on the Law of Insurance (Second Series)", "CA", 1993, 1998], 
["CCLI (3d)", "Canadian Cases on the Law of Insurance (Third Series)", "CA", 1998, Present], 
["CCLR", "Canadian Computer Law Reporter", "CA", 1983, 1992], 
["CCLS", "Canadian Cases on the Law of Securities", "CA", 1993, 1998], 
["CCLT", "Canadian Cases on the Law of Torts", "CA", 1976, 1990],
["CCLT (2d)", "Canadian Cases on the Law of Torts (Second Series)", "CA", 1990, 2000], 
["CCLT (3d)", "Canadian Cases on the Law of Torts (Third Series)", "CA", 2000, Present], 
["CCPB", "Canadian Cases on Pensions and Benefits", "CA", 1994, Present], 
["CCRI", "Conseil canadien des relations industrielles, motif de décision", "CA", 1999, Present], 
["CCRTD", "Conseil canadien des relations du travail, décisions", "CA", 1949, 1974], 
["CCRTDI", "Conseil canadien des relations du travail, décisions et informations", "CA", 1974, 1998], 
["CCTCTD", "Commission canadienne des transports, comité des télécommunications - décisions", "CA", 1973, 1976],
["CCTCTEP", "Commission canadienne des transports, comité des transports par eau - permis", "CA", 1976, 1976], 
["CCTCTO", "Commission canadienne des transports, comité des télécommunications - ordonnances", "CA", 1975, 1976], 
["CCTCTO", "Commission canadienne des transports - ordonnances", "CA", 1972, 1987], 
["CDB-C", "Collection de décisions de Bas-Canada", "CA", 1847, 1891], 
["CEB", "Canadian Employment Benefits and Pension Guide Reports", "CA", 1995, Present], 
["CEDH", "Cour européenne des Droits de l'Homme", "EU", 1960, Present], 
["CEDH (Sér A)", "Publications de la Court européenne des Droits de l'Homme : Série A : Arrêts et décisions", "EU", 1960, 1999], 
["CEDH (Sér B)", "Publications de la Court européenne des Droits de l'Homme : Série B : Mémoires, plaidoiries et documents", "EU", 1961, 1999], 
["CEGSB", "Crown Employees Grievance Settlement Board Decisions", "CA (ON)", 1976, 1997], 
["CELR", "Canadian Environmental Law Reports", "CA", 1978, 1985], 
["CELR (NS)", "Canadian Environmental Law Reports (New Series)", "CA", 1986, Present], 
["CER", "Canada Customs and Excise Reports", "CA", 1980, 1989], 
["CFLC", "Canadian Family Law Cases", "CA", 1959, 1977], 
["CFP", "Recueil des décisions des comités d'appel de la fonction publique", "CA (QC)", 1980, 1989]]


Semi = [["AR", "Alberta Reports", 1976, Present], 
		["Alta AR", "Alberta Law Reports", 1908, 1932], 
		["BCR", "British Columbia Reports", 1867, 1947], 
		["BR", "Recueils de jurisprudence du Quebec : Cour du Banc de la Reine/de Roi", 1892, 1969], 
		["CA", "Recueils de jurisprudence du Quebec : Cour d'appel", 1970, 1985], 
		["CBES", "Recueils de jurisprudence du Quebec : Cour de bien-etre social", 1975, 1985],
		["CP", "Recueils de jurisprudence du Quebec : Cour provinciale", 1975, 1987]
		["CS", "Recueils de jurisprudence du Quebec : Cour superieure", 1967, Present]
		["CSP", "Recueils de jurisprudence du Quebec : Cour des Sessions de la paix", 1975, Present]
		["Man R", "Manitoba Reports", 1883, 1961]
		["NBR", "New Brunswick Reports (2d)", 1969, Present]
		["Nfld & PEIR", "Newfoundland & Prince Edward Island Reports", 1971, Present]
		["NSR", "Nova Scotia Reports", 1965, 1969]
		["NSR (2d)", "Nova Scotia Reports (Second Series)", 1969, Present]
		["NWTR", "Northwest Territories Reports", 1983, 1998]
		["OLR", "Ontario Law Reports", 1900, 1931]
		["OR", "Ontario Reports", 1931, 1973]
		["OR (2d)", "Ontario Reports (Second Series)", 1973, Present]
		["OWN", "Ontario Weekly Notes", 1909, 1962]
		["RJQ", "Recueils de jurisprudence du Quebec", 1975, Present]
		["Sask LR", "Saskatchewan Law Reports", 1907, 1931]
		["Terr LR", "Territories Law Reports", 1885, 1907]
		["TJ", "Recueils de jurisprudence du Quebec : Tribunal de la jeunesse", 1975, Present]
		["YR", "Yukon Reports", 1986, 1989]]
		
		
		'''
